-- Curated, pre-analysed media from docs/ASSET-INVENTORY.md.
create unique index if not exists media_assets_public_url_idx on public.media_assets(public_url);

insert into public.media_assets (
  file_name, public_url, mime_type, width, height, orientation, source_kind,
  category, subjects, mood, tags, quality_score, sharpness_score, crop_safe,
  faces_visible, focal_x, focal_y, alt_text, excluded, archived
)
values
  ('WhatsApp Image 2026-06-30 at 23.38.18.jpeg','/media/library/real-01.webp','image/webp',900,1600,'portrait','real_photo','Recruitment','Cinci membri la o masă de proiect în aer liber','prietenos, practic',array['recruitment','members','collaboration'],0.82,0.78,true,true,0.50,0.46,'Cinci membri Interact pregătind materiale la o masă în aer liber',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.22 (1).jpeg','/media/library/real-02.webp','image/webp',1179,1545,'portrait','real_photo','Events','Masă aglomerată de eveniment și selfie spontan','energic, candid',array['events','community','candid'],0.80,0.76,false,true,0.52,0.52,'Moment spontan în jurul unei mese la un eveniment Interact',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.22.jpeg','/media/library/real-03.webp','image/webp',1098,1600,'portrait','real_photo','Events','Grup într-un coridor din culisele unui eveniment','intim, spontan',array['events','backstage','members'],0.70,0.66,false,true,0.50,0.48,'Membri Interact într-un moment din culisele unui eveniment',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.26.jpeg','/media/library/real-04.webp','image/webp',1179,654,'landscape','real_photo','Members','Grup mare în aer liber cu diplome','mândru, colectiv',array['members','community','recruitment','certificates'],0.84,0.80,true,true,0.50,0.55,'Grup de elevi Interact ținând diplome la finalul unei activități',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (1).jpeg','/media/library/real-05.webp','image/webp',1600,1200,'landscape','real_photo','Archived','Grup caritabil de sărbători cu copii','cald, caritabil',array['projects','holiday','consent-required'],0.82,0.78,true,true,0.50,0.50,'Grup Interact la o activitate caritabilă de sărbători',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (2).jpeg','/media/library/real-06.webp','image/webp',900,1600,'portrait','real_photo','Interviews','Panel cu trei persoane și proiecție','calm, reflexiv',array['interviews','panel','projects'],0.79,0.76,true,true,0.50,0.60,'Trei elevi într-o discuție de tip panel',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (3).jpeg','/media/library/real-07.webp','image/webp',1200,1600,'portrait','real_photo','Recruitment','Elevi colaborând pe materiale tipărite','concentrat, curios',array['recruitment','collaboration','process'],0.86,0.84,true,true,0.52,0.52,'Elevi colaborând în jurul unor materiale de proiect',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (4).jpeg','/media/library/real-08.webp','image/webp',590,787,'portrait','real_photo','Members','Trei membri la un stand Rotary','luminos, apropiat',array['projects','members','rotary'],0.64,0.60,true,true,0.50,0.50,'Trei membri Interact la un stand Rotary în aer liber',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (5).jpeg','/media/library/real-09.webp','image/webp',590,787,'portrait','real_photo','Members','Trei membri cu semnul proiectului','jucăuș, public',array['projects','members','rotary'],0.64,0.60,true,true,0.50,0.50,'Trei membri Interact prezentând un proiect la stand',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (6).jpeg','/media/library/real-10.webp','image/webp',1179,1560,'portrait','real_photo','Backgrounds','Stand Rotary cu afișe și produse','luminos, civic',array['projects','details','venue'],0.81,0.79,true,false,0.50,0.52,'Detalii de la un stand de proiect Interact și Rotary',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (7).jpeg','/media/library/real-11.webp','image/webp',929,1600,'portrait','real_photo','Backgrounds','Materiale și borcane pe o masă de proiect','tactil, organizat',array['projects','details','texture'],0.80,0.76,true,false,0.52,0.52,'Materiale pregătite pentru un proiect Interact în aer liber',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (8).jpeg','/media/library/real-12.webp','image/webp',1600,1200,'landscape','real_photo','Archived','Grup caritabil într-o sală comunitară','cald, generos',array['projects','community','consent-required'],0.82,0.78,true,true,0.50,0.50,'Voluntari Interact la o activitate caritabilă de sărbători',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (9).jpeg','/media/library/real-13.webp','image/webp',1600,1200,'landscape','real_photo','Archived','Voluntari alături de o familie beneficiară','serios, uman',array['projects','beneficiaries','consent-required'],0.81,0.79,false,true,0.50,0.50,'Voluntari Interact în timpul unei vizite comunitare',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (10).jpeg','/media/library/real-14.webp','image/webp',1170,1547,'portrait','real_photo','Members','Doi membri ținând ecusoane','personal, festiv',array['members','recruitment','badges'],0.68,0.62,true,true,0.50,0.46,'Doi membri Interact prezentând ecusoane după o activitate',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (11).jpeg','/media/library/real-15.webp','image/webp',1200,1600,'portrait','real_photo','Archived','Trei membri în echipament medical de protecție','responsabil, clinic',array['projects','medical','consent-required'],0.78,0.76,true,true,0.50,0.50,'Voluntari Interact în echipament de protecție pentru o activitate medicală',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (12).jpeg','/media/library/real-16.webp','image/webp',1200,1600,'portrait','real_photo','Archived','Doi voluntari cu flori lângă un spital','grijuliu, optimist',array['projects','medical','consent-required'],0.80,0.77,true,true,0.50,0.50,'Doi voluntari Interact cu flori în cadrul unei activități sociale',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (13).jpeg','/media/library/real-17.webp','image/webp',1600,1066,'landscape','real_photo','Members','Echipă la un eveniment Rotary','ceremonial, îngrijit',array['members','rotary','partnerships'],0.84,0.82,true,true,0.50,0.50,'Echipa Interact la un eveniment Rotary',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (14).jpeg','/media/library/real-18.webp','image/webp',1600,1200,'landscape','real_photo','Recruitment','Membri în fața unui fundal Interact District','conectat, oficial',array['recruitment','members','district','branding'],0.86,0.84,true,true,0.50,0.50,'Membri Interact Sf. Sava la un eveniment de district',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (15).jpeg','/media/library/real-19.webp','image/webp',1600,1200,'landscape','real_photo','Members','Grup într-o călătorie cu autocarul','relaxat, tineresc',array['members','community','travel','candid'],0.83,0.79,false,true,0.50,0.50,'Membri Interact într-un moment relaxat dintr-o călătorie',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (16).jpeg','/media/library/real-20.webp','image/webp',1600,1200,'landscape','real_photo','Events','Șase membri cu ecusoane într-o sală de eveniment','încrezător, organizat',array['events','operations','members','check-in'],0.85,0.82,true,true,0.50,0.50,'Echipa de organizare Interact într-o sală de eveniment',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (17).jpeg','/media/library/real-21.webp','image/webp',1600,1200,'landscape','real_photo','Recruitment','Grup mare pe o scară de marmură','premium, colectiv',array['recruitment','members','team','branding'],0.92,0.90,true,true,0.50,0.52,'Echipa Interact Sf. Sava reunită pe o scară interioară',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (18).jpeg','/media/library/real-22.webp','image/webp',900,1600,'portrait','real_photo','Members','Doi membri ținând un clopot ceremonial','ceremonial, prietenos',array['members','board','governance'],0.80,0.78,true,true,0.50,0.48,'Doi membri Interact cu un obiect ceremonial al clubului',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (19).jpeg','/media/library/real-23.webp','image/webp',1200,1600,'portrait','real_photo','Events','Mână ținând fotografii tipărite de la evenimente','nostalgic, tactil',array['events','archive','details','memories'],0.70,0.65,true,false,0.50,0.52,'Fotografii tipărite din arhiva evenimentelor Interact',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (20).jpeg','/media/library/real-24.webp','image/webp',1111,726,'landscape','real_photo','Events','Membri dansând la un eveniment live','energic, cinematografic',array['events','dance','community','cinematic'],0.88,0.84,false,true,0.50,0.48,'Membri Interact dansând într-un moment energic la un eveniment',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (21).jpeg','/media/library/real-25.webp','image/webp',1200,1600,'portrait','real_photo','Archived','Duplicat al fotografiei cu amintiri tipărite','nostalgic',array['duplicate','events','archive'],0.65,0.62,true,false,0.50,0.50,'Duplicat arhivat din seria de fotografii tipărite',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (22).jpeg','/media/library/real-26.webp','image/webp',1111,726,'landscape','real_photo','Archived','Duplicat al fotografiei de dans','energic',array['duplicate','events'],0.84,0.82,false,true,0.50,0.50,'Duplicat arhivat al momentului de dans de la eveniment',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (23).jpeg','/media/library/real-27.webp','image/webp',900,1600,'portrait','real_photo','Archived','Duplicat al fotografiei ceremoniale','ceremonial',array['duplicate','members'],0.76,0.74,true,true,0.50,0.50,'Duplicat arhivat al fotografiei ceremoniale de club',true,true),
  ('WhatsApp Image 2026-06-30 at 23.38.27 (24).jpeg','/media/library/real-28.webp','image/webp',900,1600,'portrait','real_photo','Recruitment','Grup relaxat în jurul unei mese din curte','familiar, relaxat',array['recruitment','members','community','candid'],0.81,0.78,true,true,0.50,0.50,'Membri Interact într-un moment relaxat în curtea liceului',false,false),
  ('WhatsApp Image 2026-06-30 at 23.38.27.jpeg','/media/library/real-29.webp','image/webp',1179,889,'landscape','real_photo','Hero','Grup mare de elevi la Curtea Veche','local, documentar, autentic',array['hero','recruitment','members','bucharest'],0.91,0.86,true,true,0.50,0.58,'Grup de elevi Interact în centrul vechi al Bucureștiului',false,false)
on conflict (public_url) do update set
  category = excluded.category,
  subjects = excluded.subjects,
  mood = excluded.mood,
  tags = excluded.tags,
  quality_score = excluded.quality_score,
  sharpness_score = excluded.sharpness_score,
  crop_safe = excluded.crop_safe,
  faces_visible = excluded.faces_visible,
  focal_x = excluded.focal_x,
  focal_y = excluded.focal_y,
  alt_text = excluded.alt_text,
  excluded = excluded.excluded,
  archived = excluded.archived;

insert into public.media_assets (
  file_name, public_url, mime_type, width, height, orientation, source_kind,
  category, subjects, mood, tags, quality_score, sharpness_score, crop_safe,
  faces_visible, focal_x, focal_y, alt_text, generation_tool,
  generation_prompt, generation_job_id
)
values
  ('hero-desktop.webp','/media/hero-desktop.webp','image/webp',2200,1238,'landscape','edited_photo','Hero','Grupul real de la Curtea Veche într-un cadru extins 16:9','local, documentar, cinematic',array['hero','bucharest','members','desktop'],0.93,0.90,true,true,0.50,0.62,'Grup de elevi Interact în centrul vechi al Bucureștiului','Higgsfield Outpaint','', 'a7117b7c-b2cc-47a6-b097-26ec7560ceba'),
  ('hero-mobile.webp','/media/hero-mobile.webp','image/webp',1040,1300,'portrait','edited_photo','Hero','Grupul real de la Curtea Veche într-un cadru extins 4:5','local, documentar, tineresc',array['hero','bucharest','members','mobile'],0.91,0.88,true,true,0.50,0.58,'Grup de elevi Interact în centrul vechi al Bucureștiului','Higgsfield Outpaint','', 'fde3e46c-a8a1-4551-bcf0-7cd61f6f7fbb'),
  ('interview-editorial.webp','/media/interview-editorial.webp','image/webp',1600,1067,'landscape','higgsfield','Interviews','Trei adolescenți într-o discuție calmă la o masă','calm, primitor, editorial',array['interviews','students','discussion','scheduling'],0.86,0.88,true,true,0.53,0.55,'Trei elevi discutând într-o sală de clasă înaintea unui interviu','Higgsfield · Nano Banana Pro','A realistic editorial documentary photograph for a Romanian youth organization website. In a modest meeting room inside an old Bucharest high school, three Romanian teenagers aged 16 to 18 sit at a simple wooden table during a friendly interview: one candidate and two student interviewers. Camera at table height, 35mm documentary framing. An open notebook, blue pen, phone face-down, and a plain scheduling grid are on the table; the printed lines are softly out of focus and contain no legible words. Casual contemporary clothes, attentive relaxed body language, candid expressions, authentic natural skin texture, slightly imperfect smartphone-photo character. Warm neutral ceiling light mixed with cool daylight from a tall window. Restrained beige, charcoal and natural wood palette, with one small cyan lanyard detail. Leave quiet negative space at right for website copy. The atmosphere is welcoming, serious but not intimidating, and unmistakably a real school club rather than a company. No logos, no readable text, no American campus design, no blazers or business clothes, no hospital, medical, legal or forensic props, no staged advertisement, no glamour lighting, no plastic skin, no distorted hands, no extra fingers, no duplicate people, no watermark.','e533cae2-913f-46c1-a59e-b56624db8085')
on conflict (public_url) do update set
  generation_tool = excluded.generation_tool,
  generation_prompt = excluded.generation_prompt,
  generation_job_id = excluded.generation_job_id,
  quality_score = excluded.quality_score,
  alt_text = excluded.alt_text;
