// All Romanian UI strings in one place.
// Never hardcode copy inline — import from here.

export const copy = {
  app: {
    name: "SavaPass",
    tagline: "by Interact Sf. Sava",
    taglineFull: "Biletul tău pentru fiecare seară Interact.",
  },
  event: {
    seatsLeft: (n: number) => `${n} loc${n === 1 ? "" : "uri"} rămase`,
    soldOut: "Sold out",
    buyTicket: (price: number) => `Cumpără bilet — ${price} RON`,
    doorsLabel: "Porți",
    venueLabel: "Locație",
    priceLabel: "Preț",
    program: "Program",
    perks: "Ce primești",
    about: "Despre eveniment",
    pastEvents: "Evenimente trecute",
    currentEvent: "Evenimentul curent",
    nextEvent: "Următorul eveniment",
  },
  checkout: {
    title: "Plată",
    eyebrow: "PLATĂ SECURIZATĂ",
    namePlaceholder: "Prenume și nume",
    emailPlaceholder: "Adresa ta de email",
    gdprLabel: "Sunt de acord cu prelucrarea datelor personale.",
    submitButton: (price: number) => `Plătește ${price} RON`,
    processing: "Se procesează…",
    soldOutError: "Ne pare rău, biletele s-au terminat.",
  },
  success: {
    title: "Ești înăuntru.",
    subtitle: "Biletul tău a fost emis.",
    waiting: "Se emite biletul…",
    viewTicket: "Vezi biletul",
    emailSent: (email: string) => `Am trimis biletul pe ${email}`,
  },
  ticket: {
    eyebrow: "BILETUL TĂU",
    valid: "Valid",
    used: "Folosit",
    checkedIn: "Înăuntru",
    void: "Anulat",
    showAtDoor: "Arată acest cod la intrare",
  },
  scanner: {
    eyebrow: "ORGANIZATOR · SCANARE",
    instructions: "Îndreaptă camera spre codul QR",
    or: "sau introdu manual",
    codePlaceholder: "Cod bilet (ex. K7F2MQ)",
    verdictOk: (name: string) => `${name} · Intrat`,
    verdictAlreadyIn: (name: string) => `${name} · Deja înăuntru`,
    verdictAlreadyUsed: (name: string) => `${name} · Bilet folosit`,
    verdictInvalid: "Cod necunoscut",
    verdictVoid: "Bilet anulat",
  },
  admin: {
    title: "Dashboard",
    sold: "Bilete vândute",
    revenue: "Venit total",
    checkedIn: "Check-in",
    capacity: "Capacitate",
    attendees: "Participanți",
    scanLog: "Scanări recente",
    exportCsv: "Exportă CSV",
    pastEvents: "Evenimente trecute",
    editEvent: "Editează evenimentul",
    publishEvent: "Publică evenimentul",
    archiveEvent: "Arhivează",
    statusActive: "Activ",
    statusDraft: "Ciornă",
    statusPast: "Trecut",
  },
  errors: {
    notFound: "Pagina nu există",
    notFoundSub: "Încearcă să revii la pagina principală.",
    backHome: "Înapoi acasă",
    generic: "Ceva a mers greșit.",
    ticketInvalid: "Bilet invalid sau expirat.",
  },
  nav: {
    home: "Acasă",
    myTicket: "Cumpără bilet",
    scanner: "Scanare",
    admin: "Dashboard",
    login: "Intră în cont",
    logout: "Ieși din cont",
  },
  landing: {
    howItWorks: "Cum funcționează",
    step1Title: "Alege evenimentul",
    step1Body: "Un singur eveniment activ la un moment dat. Fără noise, fără filtre.",
    step2Title: "Plătești online",
    step2Body: "Checkout rapid, card sau transfer. Datele tale sunt în siguranță.",
    step3Title: "Intri cu QR",
    step3Body: "Primești codul pe email și în aplicație. Îl arăți la intrare — gata.",
    aboutInteract: "Despre Interact",
    aboutBody:
      "Interact Sf. Sava este clubul studențesc al Colegiului Național Sfântul Sava, afiliat Rotary International. Organizăm proiecte culturale, sociale și educative — iar fiecare bilet SavaPass susține direct o cauză.",
    stats: {
      editions: "ediții",
      tickets: "bilete emise",
      donated: "RON donați",
    },
  },
} as const;
