import type { EventRecord } from "@/lib/event-types";

export const GOLDEN_HOUR = {
  id: "instagram-Db-lR7Qtfy2",
  slug: "golden-hour-2026",
  title: "Golden Hour",
  subtitle: "Ultima pagină din vara aceasta.",
  dateLabel: "Dum · 30 aug · 20:00",
  dateLong: "Duminică, 30 august 2026",
  startDate: "2026-08-30",
  endDate: "2026-08-31",
  startTime: "20:00",
  endTime: "02:00",
  venue: "NOOK Club",
  priceRon: 35,
  minimumConsumptionRon: 50,
  poster: "/instagram/Db-lR7Qtfy2-full.jpg",
  checkoutHref: "/despre",
  detailHref: "/evenimente/golden-hour-2026",
  instagramUrl: "https://www.instagram.com/interact.sfsava/p/Db-lR7Qtfy2/",
} as const;

export const GOLDEN_HOUR_EVENT = {
  id: GOLDEN_HOUR.id,
  slug: GOLDEN_HOUR.slug,
  title: GOLDEN_HOUR.title,
  subtitle: GOLDEN_HOUR.subtitle,
  shortDescription: "Închidem vara la NOOK Club alături de Interact Sf. Sava, OCTO și Cișmigiu.",
  fullDescription: "Golden Hour este petrecerea de final de vară organizată de Interact Sf. Sava împreună cu OCTO și Cișmigiu. Accesul începe la 20:00, iar evenimentul continuă până la 02:00.",
  startDate: GOLDEN_HOUR.startDate,
  endDate: GOLDEN_HOUR.endDate,
  startTime: GOLDEN_HOUR.startTime,
  endTime: GOLDEN_HOUR.endTime,
  timezone: "Europe/Bucharest",
  venueName: GOLDEN_HOUR.venue,
  category: "club",
  donationText: `Donație minimă de acces: ${GOLDEN_HOUR.priceRon} lei. Consumație minimă în locație: ${GOLDEN_HOUR.minimumConsumptionRon} lei.`,
  ticketPrice: `${GOLDEN_HOUR.priceRon} lei`,
  internalTicketingUrl: GOLDEN_HOUR.checkoutHref,
  collaborators: ["Interact Sf. Sava", "Interact OCTO", "Interact Cișmigiu"],
  sponsors: [],
  coverImage: {
    src: GOLDEN_HOUR.poster,
    alt: "Afișul roz Golden Hour",
    type: "poster",
    width: 1350,
    height: 1688,
  },
  gallery: [
    {
      src: "/instagram/Db-lR7Qtfy2-full.jpg",
      alt: "Afișul principal Golden Hour",
      type: "poster",
      width: 1350,
      height: 1688,
      sourcePostUrl: "https://www.instagram.com/interact.sfsava/p/Db-lR7Qtfy2/",
    },
    {
      src: "/instagram/Db-lIvmtsK5.jpg",
      alt: "Afiș Golden Hour cu data de 30 august",
      type: "poster",
      width: 640,
      height: 640,
      sourcePostUrl: "https://www.instagram.com/interact.sfsava/p/Db-lIvmtsK5/",
    },
    {
      src: "/instagram/Db-lXIsNJXf.jpg",
      alt: "Afiș Golden Hour cu donația minimă de 35 lei",
      type: "poster",
      width: 640,
      height: 640,
      sourcePostUrl: "https://www.instagram.com/interact.sfsava/p/Db-lXIsNJXf/",
    },
  ],
  instagramPostUrls: [
    "https://www.instagram.com/interact.sfsava/p/Db-lR7Qtfy2/",
    "https://www.instagram.com/interact.sfsava/p/Db-lIvmtsK5/",
    "https://www.instagram.com/interact.sfsava/p/Db-lXIsNJXf/",
  ],
  instagramPostIds: ["Db-lR7Qtfy2", "Db-lIvmtsK5", "Db-lXIsNJXf"],
  originalCaption: "Golden Hour · 30 august · 20:00–02:00 · NOOK Club.",
  publishedAt: "2026-08-13",
  eventStatus: "upcoming",
  publishingStatus: "published",
  extractionConfidence: "high",
  missingFields: ["charitableCause", "address"],
  lastSyncedAt: "2026-08-15T00:00:00+03:00",
} satisfies EventRecord;
