import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../lib/supabase/types";
import { signTicketWithSecret } from "../lib/qr-token-core";
import "./safe-test-database";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key) throw new Error("Supabase test environment is missing");
const db=createClient<Database>(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const secret="database-integration-test-secret-32-characters";
const authIds:string[]=[]; const orderIds:string[]=[]; const ticketIds:string[]=[];
let boardId="",scannerId="",memberId="",member2Id="",meetingId="",eventId="";
let memberRef="",member2Ref="",inactiveRef="",boardRef="";
let reservedTicket="",paidTicket="",cancelledTicket="",expiredTicket="",concurrentTicket="";

async function createTestUser(label:string,role:"board"|"scanner"|null,status="active") { const email=`savapass-test-${label}-${randomUUID()}@example.com`; const {data,error}=await db.auth.admin.createUser({email,password:`Test-${randomUUID()}-A1!`,email_confirm:true,user_metadata:{name:`Test ${label}`}}); if(error||!data.user)throw error??new Error("user create failed"); authIds.push(data.user.id); const ref=randomUUID(); const {error:profileError}=await db.from("profiles").upsert({id:data.user.id,full_name:`Test ${label}`,email,role,membership_status:status,member_ref:ref}); if(profileError)throw profileError; return{id:data.user.id,ref}; }
async function createTicket(status:Database["public"]["Enums"]["ticket_status"],orderStatus:Database["public"]["Enums"]["order_status"],amount=1000){const orderId=randomUUID(),ticketId=randomUUID();orderIds.push(orderId);ticketIds.push(ticketId);let result=await db.from("orders").insert({id:orderId,event_id:eventId,buyer_name:"Test Buyer",buyer_email:`test-${ticketId}@example.com`,amount_bani:amount,status:orderStatus,paid_at:orderStatus==="paid"?new Date().toISOString():null});if(result.error)throw result.error;result=await db.from("tickets").insert({id:ticketId,order_id:orderId,event_id:eventId,code:ticketId.slice(0,8).toUpperCase(),qr_token:signTicketWithSecret(secret,ticketId),holder_name:"Test Buyer",holder_email:`test-${ticketId}@example.com`,status,expires_at:status==="reserved"?new Date(Date.now()+3_600_000).toISOString():null,payment_confirmed_at:status==="paid"?new Date().toISOString():null});if(result.error)throw result.error;return ticketId;}
function rpcResult(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?String((value as {result?:unknown}).result):"error";}

before(async()=>{const board=await createTestUser("Board","board");boardId=board.id;boardRef=board.ref;const scanner=await createTestUser("Scanner","scanner");scannerId=scanner.id;const member=await createTestUser("Member",null);memberId=member.id;memberRef=member.ref;const member2=await createTestUser("Member2",null);member2Id=member2.id;member2Ref=member2.ref;const inactive=await createTestUser("Inactive",null,"inactive");inactiveRef=inactive.ref;meetingId=randomUUID();const {error:meetingError}=await db.from("meetings").insert({id:meetingId,title:"Test întâlnire izolată",description:"Test automat",starts_at:new Date(Date.now()+300_000).toISOString(),ends_at:new Date(Date.now()+7_200_000).toISOString(),location:"Test",attendance_opens_at:new Date(Date.now()-3_600_000).toISOString(),attendance_closes_at:new Date(Date.now()+3_600_000).toISOString(),status:"attendance_open",created_by:boardId});if(meetingError)throw meetingError;const{data:event}=await db.from("events").select("id").eq("status","active").limit(1).maybeSingle();if(!event)throw new Error("An active event is required for ticket integration tests");eventId=event.id;reservedTicket=await createTicket("reserved","pending");paidTicket=await createTicket("paid","paid");cancelledTicket=await createTicket("cancelled","paid");expiredTicket=await createTicket("expired","paid");concurrentTicket=await createTicket("paid","paid");});

after(async()=>{if(authIds.length)await db.from("audit_logs").delete().in("actor_id",authIds);if(meetingId){await db.from("attendance_corrections").delete().eq("meeting_id",meetingId);await db.from("meeting_attendance").delete().eq("meeting_id",meetingId);await db.from("attendance_scans").delete().eq("meeting_id",meetingId);await db.from("meetings").delete().eq("id",meetingId);}if(ticketIds.length){await db.from("cash_payment_confirmations").delete().in("ticket_id",ticketIds);await db.from("scans").delete().in("ticket_id",ticketIds);await db.from("tickets").delete().in("id",ticketIds);}if(orderIds.length)await db.from("orders").delete().in("id",orderIds);if(authIds.length)await db.from("profiles").delete().in("id",authIds);for(const id of authIds)await db.auth.admin.deleteUser(id);});

test("3. board member can scan a valid member QR",async()=>{const{data,error}=await db.rpc("record_meeting_attendance",{p_meeting_id:meetingId,p_member_ref:memberRef,p_scanner_user_id:boardId,p_token_fingerprint:"a".repeat(64),p_device_metadata:{test:true}});assert.ifError(error);assert.equal(rpcResult(data),"accepted");});
test("4. duplicate member scan does not create a second attendance record",async()=>{const{data}=await db.rpc("record_meeting_attendance",{p_meeting_id:meetingId,p_member_ref:memberRef,p_scanner_user_id:boardId,p_token_fingerprint:"b".repeat(64),p_device_metadata:{test:true}});assert.equal(rpcResult(data),"already_present");const{count}=await db.from("meeting_attendance").select("id",{count:"exact",head:true}).eq("meeting_id",meetingId).eq("member_id",memberId);assert.equal(count,1);});
test("5. two concurrent member scans create only one attendance record",async()=>{const calls=["c","d"].map((character)=>db.rpc("record_meeting_attendance",{p_meeting_id:meetingId,p_member_ref:member2Ref,p_scanner_user_id:boardId,p_token_fingerprint:character.repeat(64),p_device_metadata:{test:true}}));const results=(await Promise.all(calls)).map((response)=>rpcResult(response.data)).sort();assert.deepEqual(results,["accepted","already_present"]);const{count}=await db.from("meeting_attendance").select("id",{count:"exact",head:true}).eq("meeting_id",meetingId).eq("member_id",member2Id);assert.equal(count,1);});
test("9. board member cannot scan themselves",async()=>{const{data}=await db.rpc("record_meeting_attendance",{p_meeting_id:meetingId,p_member_ref:boardRef,p_scanner_user_id:boardId,p_token_fingerprint:"e".repeat(64),p_device_metadata:{test:true}});assert.equal(rpcResult(data),"self_scan_blocked");});
test("10. inactive member QR is rejected",async()=>{const{data}=await db.rpc("record_meeting_attendance",{p_meeting_id:meetingId,p_member_ref:inactiveRef,p_scanner_user_id:boardId,p_token_fingerprint:"f".repeat(64),p_device_metadata:{test:true}});assert.equal(rpcResult(data),"inactive_member");});
test("11. RESERVED ticket scan confirms cash and checks in atomically",async()=>{
  const{data,error}=await db.rpc("check_in_ticket",{p_ticket_id:reservedTicket,p_actor_id:scannerId,p_token_fingerprint:"1".repeat(64),p_device_metadata:{test:true}});
  assert.ifError(error);assert.equal(rpcResult(data),"accepted");
  const[{data:ticket},{data:order},{count:confirmations},{data:scan}]=await Promise.all([
    db.from("tickets").select("status, payment_confirmed_at, checked_in_at, order_id").eq("id",reservedTicket).single(),
    db.from("orders").select("status, paid_at").eq("id",orderIds[0]).single(),
    db.from("cash_payment_confirmations").select("id",{count:"exact",head:true}).eq("ticket_id",reservedTicket),
    db.from("scans").select("result, action, previous_status, new_status").eq("ticket_id",reservedTicket).eq("action","check_in").single(),
  ]);
  assert.equal(ticket?.status,"checked_in");assert.ok(ticket?.payment_confirmed_at);assert.ok(ticket?.checked_in_at);
  assert.equal(order?.status,"paid");assert.ok(order?.paid_at);assert.equal(confirmations,1);
  assert.deepEqual(scan,{result:"accepted",action:"check_in",previous_status:"reserved",new_status:"checked_in"});
});
test("12. PAID ticket can be checked in",async()=>{const{data}=await db.rpc("check_in_ticket",{p_ticket_id:paidTicket,p_actor_id:scannerId,p_token_fingerprint:"2".repeat(64),p_device_metadata:{test:true}});assert.equal(rpcResult(data),"accepted");});
test("13. CHECKED_IN ticket returns a duplicate result",async()=>{const{data}=await db.rpc("check_in_ticket",{p_ticket_id:paidTicket,p_actor_id:scannerId,p_token_fingerprint:"3".repeat(64),p_device_metadata:{test:true}});assert.equal(rpcResult(data),"already_checked_in");const{count}=await db.from("scans").select("id",{count:"exact",head:true}).eq("ticket_id",paidTicket).eq("action","check_in").eq("result","accepted");assert.equal(count,1);});
test("14. CANCELLED and EXPIRED tickets are rejected",async()=>{const[cancelled,expired]=await Promise.all([db.rpc("check_in_ticket",{p_ticket_id:cancelledTicket,p_actor_id:scannerId,p_token_fingerprint:"4".repeat(64),p_device_metadata:{test:true}}),db.rpc("check_in_ticket",{p_ticket_id:expiredTicket,p_actor_id:scannerId,p_token_fingerprint:"5".repeat(64),p_device_metadata:{test:true}})]);assert.equal(rpcResult(cancelled.data),"cancelled");assert.equal(rpcResult(expired.data),"expired");});
test("15. concurrent ticket scans create only one check-in",async()=>{const calls=["6","7"].map((character)=>db.rpc("check_in_ticket",{p_ticket_id:concurrentTicket,p_actor_id:scannerId,p_token_fingerprint:character.repeat(64),p_device_metadata:{test:true}}));const results=(await Promise.all(calls)).map((response)=>rpcResult(response.data)).sort();assert.deepEqual(results,["accepted","already_checked_in"]);const{count}=await db.from("scans").select("id",{count:"exact",head:true}).eq("ticket_id",concurrentTicket).eq("action","check_in").eq("result","accepted");assert.equal(count,1);});
test("20. manual attendance correction creates audit records",async()=>{const corrected=await db.rpc("correct_meeting_attendance",{p_meeting_id:meetingId,p_member_id:memberId,p_new_status:"reversed",p_reason:"Corecție automată de test",p_actor_id:boardId});assert.equal(rpcResult(corrected.data),"corrected");const[{count:corrections},{count:audits}]=await Promise.all([db.from("attendance_corrections").select("id",{count:"exact",head:true}).eq("meeting_id",meetingId).eq("member_id",memberId),db.from("audit_logs").select("id",{count:"exact",head:true}).eq("actor_id",boardId).eq("action","attendance.corrected")]);assert.equal(corrections,1);assert.equal(audits,1);});
